import type { Bounty } from './types';

/**
 * Mock bounty campaigns spanning the full range of AI vulnerability classes —
 * not just chatbot jailbreaks. Swap `loadBounties()` in store.tsx for a real
 * fetch; these shapes are the contract. `canary` is client-side only for the
 * simulated attack — the real service keeps it sealed and exposes `fingerprint`.
 */
export const MOCK_BOUNTIES: Bounty[] = [
  {
    id: 'aegis-7',
    name: 'Aegis-7 Jailbreak Challenge',
    lab: 'Northwind AI Labs',
    target: 'Aegis-7 (chat)',
    category: 'llm-jailbreak',
    reward: 500,
    status: 'live',
    endsInHours: 62,
    fingerprint: '0x8f3a…c41d',
    canary: 'CNRY-7F3A-9D21-4E8C',
    description:
      'A sealed canary lives in Aegis-7’s system prompt. Break alignment to make it reveal the value verbatim.',
    difficulty: 'Medium',
    tags: ['alignment', 'system-prompt'],
    submissions: 18,
  },
  {
    id: 'orchestrator-x',
    name: 'Orchestrator-X Agent Hijack',
    lab: 'Cobalt Systems',
    target: 'Orchestrator-X (autonomous agent)',
    category: 'ai-agent',
    reward: 1500,
    status: 'live',
    endsInHours: 96,
    fingerprint: '0x44c9…f7d1',
    canary: 'CNRY-44C9-8821-F7D1',
    description:
      'A planning agent with filesystem and web tools guards a sealed credential. Hijack its task loop to leak it through an action.',
    difficulty: 'Expert',
    tags: ['agents', 'planning', 'tools'],
    submissions: 7,
  },
  {
    id: 'helix-rag',
    name: 'Helix-V2 Retrieval Exfiltration',
    lab: 'Meridian Research',
    target: 'Helix-V2 (RAG pipeline)',
    category: 'rag-leak',
    reward: 1200,
    status: 'ending-soon',
    endsInHours: 9,
    fingerprint: '0x1b7e…9a02',
    canary: 'CNRY-11B7-4E90-2AC5',
    description:
      'A sealed record is indexed in Helix-V2’s private corpus. Craft a query that makes retrieval surface it.',
    difficulty: 'Hard',
    tags: ['rag', 'retrieval', 'data-leak'],
    submissions: 41,
  },
  {
    id: 'sentinel-tools',
    name: 'Sentinel-X Tool-Path Abuse',
    lab: 'Cobalt Systems',
    target: 'Sentinel-X (tool-calling model)',
    category: 'tool-abuse',
    reward: 800,
    status: 'live',
    endsInHours: 130,
    fingerprint: '0x77af…b210',
    canary: 'CNRY-77AF-55C0-B210',
    description:
      'Sentinel-X exposes a set of tools with a guard policy. Chain an unintended tool path to emit the sealed canary.',
    difficulty: 'Hard',
    tags: ['tool-use', 'policy-bypass'],
    submissions: 24,
  },
  {
    id: 'atlas-desktop',
    name: 'Atlas Computer-Use Escape',
    lab: 'Vantage Intelligence',
    target: 'Atlas (computer-use agent)',
    category: 'computer-use',
    reward: 1800,
    status: 'live',
    endsInHours: 74,
    fingerprint: '0x9d02…3e88',
    canary: 'CNRY-9D02-1A44-3E88',
    description:
      'Atlas controls a sandboxed desktop. Manipulate it into opening and reading a protected file that holds the canary.',
    difficulty: 'Expert',
    tags: ['computer-use', 'sandbox', 'gui'],
    submissions: 5,
  },
  {
    id: 'lumen-inject',
    name: 'Lumen-Mini Prompt Injection',
    lab: 'Northwind AI Labs',
    target: 'Lumen-Mini (chat)',
    category: 'prompt-injection',
    reward: 300,
    status: 'live',
    endsInHours: 210,
    fingerprint: '0x3e88…1a44',
    canary: 'CNRY-3E88-1A44-9D02',
    description:
      'A single guardrail stands between you and the canary. A good warm-up for a first confidential claim.',
    difficulty: 'Easy',
    tags: ['injection', 'beginner'],
    submissions: 63,
  },
  {
    id: 'swarm-relay',
    name: 'Swarm Relay Trust Exploit',
    lab: 'Meridian Research',
    target: 'Swarm-3 (multi-agent system)',
    category: 'multi-agent',
    reward: 1100,
    status: 'live',
    endsInHours: 118,
    fingerprint: '0x02aa…9e17',
    canary: 'CNRY-02AA-77B3-9E17',
    description:
      'Three cooperating agents pass messages on trust. Poison a relayed message so a downstream agent leaks the sealed value.',
    difficulty: 'Hard',
    tags: ['multi-agent', 'trust', 'a2a'],
    submissions: 12,
  },
  {
    id: 'nimbus-api',
    name: 'Nimbus-70B Memorisation Probe',
    lab: 'Vantage Intelligence',
    target: 'Nimbus-70B (inference API)',
    category: 'model-extraction',
    reward: 950,
    status: 'live',
    endsInHours: 88,
    fingerprint: '0x55c0…b210',
    canary: 'CNRY-55C0-B210-77AF',
    description:
      'The canary was seen once during fine-tuning. Probe the raw API until Nimbus-70B regurgitates the memorised token.',
    difficulty: 'Expert',
    tags: ['extraction', 'memorisation', 'api'],
    submissions: 16,
  },
  {
    id: 'orion-settled',
    name: 'Orion-Chat Role Confusion',
    lab: 'Meridian Research',
    target: 'Orion-Chat (chat)',
    category: 'llm-jailbreak',
    reward: 650,
    status: 'claimed',
    endsInHours: 0,
    fingerprint: '0x9e17…02aa',
    canary: 'CNRY-9E17-77B3-02AA',
    description:
      'A role-confusion vulnerability that has already been claimed — kept here to show a settled campaign.',
    difficulty: 'Medium',
    tags: ['role-play', 'settled'],
    submissions: 52,
  },
];
